### ISSUE TITLE
ACPI Error: [\_PR_.PR00] Namespace lookup failure, AE_NOT_FOUND

### ISSUE THREAD

**Issue by arypramudito** [corpnewt/CPUFriendFriend#10]
The result aml automatically file is    

   External (_PR_.PR00, DeviceObj)    // (from opcode)

    Scope (\_PR.PR00)

The original DSDT SSDT object have at DSDT.aml:
    External (_SB_.PR00, DeviceObj)    // (from opcode)

    Scope (_SB.PR00) 
     

so creating error at kernel.log 
shall manually change?

**Comment by corpnewt** [comment]
This is when creating the SSDT, correct?  If so - that's actually an issue with the ResourceConverter.sh script from CPUFriend - found [here](https://github.com/acidanthera/CPUFriend/blob/master/Tools/ResourceConverter.sh) - as that's what CPUFriendFriend leverages.

If you like, you should be able to generate the data provider kext instead - as that doesn't require specific pathing.

Either way, it's not within the scope of this project, and should be brought instead to Acidanthera.

-CorpNewt
