### ISSUE TITLE
ssdt_data has wrong CPU acpi path

### ISSUE THREAD

**Issue by 1alessandro1** [corpnewt/CPUFriendFriend#11]
Hi, I'd add the functionality from SSDTTime to specify correct CPU path for the SSDT, since on my laptop this is the ssdt generated from SSDTTime for Plug:

[SSDT-PLUG.aml.zip](https://github.com/corpnewt/CPUFriendFriend/files/6291859/SSDT-PLUG.aml.zip)

And this one instead is the one generated by CPUFriendFriend:
[ssdt_data.dsl.zip](https://github.com/corpnewt/CPUFriendFriend/files/6291863/ssdt_data.dsl.zip)

![image](https://user-images.githubusercontent.com/46293832/114305896-55534280-9ada-11eb-988b-ec0dc3db0d83.png)

As you can see the acpi path is wrong, and I had to fix that in order to correctly load it

Thank you for your attention ^_^

**Comment by 1alessandro1** [comment]
If you want to test yourself, [here](https://github.com/1alessandro1/HP-Pavilion-CE2072NL-macOS/blob/main/ACPI%20Dumps/SysReport%20-%20BIOS%20F23%20RevA.zip) yoy can find my ACPI folder

**Comment by 1alessandro1** [comment]
@corpnewt any news?

**Comment by corpnewt** [comment]
It's not an issue with CPUFriendFriend as much as it is an assumption made by the ResourceConverter.sh from the original CPUFriend repo [here](https://github.com/acidanthera/CPUFriend).  I would suggest you either reach out to them regarding it - or use the .kext created instead (as it does not rely on ACPI pathing).

-CorpNewt
