### ISSUE TITLE
[Request] add link to CPUfriend.kext to readme

### ISSUE THREAD

**Issue by Overc1ocker** [corpnewt/CPUFriendFriend#12]
Hello! I finally got CPU power management to work on my i5 8250U! However, I got stuck along the way as I didn't realize you needed CPUfrienddataprovider and CPufriend.kext. Please link to this kext in the readme or maybe add a copy of CPUfriend.kext to the repo. Thanks!

**Comment by corpnewt** [comment]
I just pushed a commit that states the requirement of CPUFriend.kext [here](https://github.com/corpnewt/CPUFriendFriend/commit/e2ba70760edc23392b6e079f7b19646b73938666).  I'd rather not include CPUFriend.kext locally as I'd have to manually keep that updated, and it's better for the user to get the version they need.

Thanks for letting me know that I'd forgotten to clearly state the .kext requirement though!

-CorpNewt
