### ISSUE TITLE
Wrong TDP-down frequency?

### ISSUE THREAD

**Issue by flo-at-work** [corpnewt/CPUFriendFriend#21]
Hello,

On the Intel ARK website the TDP-down frequency of my CPU i5-5200U (https://ark.intel.com/content/www/us/en/ark/products/85212/intel-core-i5-5200u-processor-3m-cache-up-to-2-70-ghz.html) is 600MHz but the lowest value CPUFriendFriend script is allowing is 800MHz. Is it possible by any way to generate a kext with a LFM value lower than 800Mhz?

Thanks a lot!

**Comment by corpnewt** [comment]
The script does not restrict the value you can type in - it just lists examples.  If you want 600MHz, when it asks, just type `0x06` or similar.

-CorpNewt

**Comment by flo-at-work** [comment]
Ok thanks,

So i've typed 0x06 and I think it has produced the right kext, but when I check with Intel Power Gadget it seems that the lowest value the CPU can go is still 800mhz, even when the requested frequency is lower (check the screenshot).
Do you know by chance why macOS is not allowing the CPU to go lower than 800mhz?
For information I'm using MacBookAir7,2 as SMBIOS.

Thanks again!
![EBF9D4E3-2C84-433A-AA9D-0CDE8B231293](https://github.com/user-attachments/assets/c291e673-2adf-4546-9800-aa48a94a22a1)
