### ISSUE TITLE
No option to enter EPP value

### ISSUE THREAD

**Issue by dobitamas** [corpnewt/CPUFriendFriend#3]
Intel i5 5200U after providing the minimum frequency, it doesn't ask me about my EPP value

**Comment by corpnewt** [comment]
The script only gives the option to set the EPP value if it already exists in the X86PlatformPlugin plist that corresponds with your mac model. If that doesn't have one, it doesn't have anything to change.

-CorpNewt

**Comment by marcinkk** [comment]
I set cpu management script cpufriend fiend but I have to enter only the value of tdp-down, processors i5-5257u.  why so??
